name: Cloning Branch on repo
run-name: Github actions test
on: 
  push:
    branches: 
      - master
jobs:
  test-create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          name: vetonmilaimi/github-actions-front
      - run: git checkout -b actions-test
      - run: git push --set-upstream origin actions-test