name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: vetonmilaimi
          repo: github-actions-back
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: master.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s